### ISSUE TITLE
Selecting 'List is empty' displays error

### ISSUE THREAD

**Issue by payal-sarnot** [CreatorDev/android-provisioning-onboard-app#12]
While trying to provision if there are no clickers available then 'List is empty' text is displayed. On selecting this text app tries to login and then displays error 'Invalid clickerID. Selected clicker may no longer be connected', whereas actually there should be no action performed on selecting the same.

**Comment by krzych0** [comment]
Fixed: https://github.com/CreatorDev/android-provisioning-onboard-app/pull/15
